### ISSUE TITLE
Debian9.4: spinsim needs constant input to run

### ISSUE THREAD

**Issue by drawkula** [parallaxinc/spinsim#3]
Spinsim seems to hang after the 1st output but runs when repeatedly getting input ("</dev/null" or repeatedly hitting ENTER) on Debian9.4.

An other spinsim ...
```
$ /opt/spinsim/bin/spinsim 
Spinsim Version 0.97
usage: spinsim [options] file
The options are as follows:
     -v# Set verbosity level
     -l <filename>  List executed instructions to <filename>
     -p  Use PASM Spin interpreter
     -#  Execute # instructions
     -P  Profile Spin opcode usage
     -m# Set the hub memory size to # K-bytes
     -t# Enable the Prop 2 mode.  # specifies options
     -b# Enable the serial port and set the baudrate to # (default 115200)
     -gdb Operate as a GDB target over stdin/stdout
     -L <filename> Log GDB remote comm to <filename>
     -r <filename> Replay GDB session from <filename>
     -e Use eeprom.dat
     -d Use debugger
     -pst Use PST mode
```
... does not misbehave in this way on the same machine.

Spinsim-0.97 is there:
—▶ https://forums.parallax.com/discussion/comment/1416368/#Comment_1416368
—▶ https://forums.parallax.com/discussion/download/120918/spinsim097.zip

**Comment by davehein** [comment]
The version in this repository is a few years old.  The latest version is 0.97, and is maintained in the referenced thread on the Parallax forum.  That seems to work for you, so I suggest using that version.

**Comment by drawkula** [comment]
The beauty of VCS is not to stay on broken old code for eons.

**Comment by drawkula** [comment]
Ok... probably I should add that this repo is included as git submodule in https://github.com/dbetz/propeller-gcc and so that propeller-gcc install ends with an outdated and on some systems even unusable spinsim.

**Comment by dbetz** [comment]
Should I just remove spinsim from the propeller-gcc build? It's going to be a pain to keep it up to date with Dave's version on the forum.

Dave: Would you be willing to adopt the spinsim repository on the Parallax GitHub account and maintain spinsim there instead of on the forum?

**Comment by PropGit** [comment]
@davehein - I can add you to the permissions if you want to do this.  You could choose to update both the forum and this repo with any updates, or simply update this repo and point thread users here, for example.

**Comment by davehein** [comment]
Please add me, and I will check my latest version into the repository.  Thanks.

**Comment by drawkula** [comment]
@davehein ... many thanks!

That will help to easier keep a standalone `/opt/spinsim` updodate as well as `spinsim` as submodule of PropellerGCC.

**Comment by dbetz** [comment]
We don't actually need spinsim to be part of PropGCC as far as I know. I think the only reason we put it in there was so it would get built by David Zemon's build server to be available to people if they wanted to use it. If you have a standalone project then we can just ask David to build that separately from PropGCC.

**Comment by PropGit** [comment]
@davehein - Looks like you already have write access to this repository; I may have set that up when we created it (or someone else did?).  Please let me know if you cannot clone and then push back to it.

**Comment by drawkula** [comment]
@dbetz ... `spinsim` already was part of the older PropGCC(4) build too. I don't know whether it was needed for something while building PropGCC(4) but it is very useful for experiments without having a board at hand.

**Comment by dbetz** [comment]
Yes, I know it can be useful but it doesn't actually have to be part of the PropGCC build as long as it is built and included in any tools distribution. I guess one problem is that Parallax has never provided an installer for the command line tools, only for SimpleIDE.

**Comment by PropGit** [comment]
I don't know why, but your account wasn't in the contributors list... doesn't make sense to me because you're the only contributor in the repo's history (so far) and I did not remove you from it.  I've reinstated you via emailed invitation.

**Comment by dbetz** [comment]
Thanks! I've pushed Dave's 0.97. Dave can take over from here maintaining spinsim.

**Comment by drawkula** [comment]
Solved.
(See https://github.com/parallaxinc/spinsim/issues/4 too.)
